### ISSUE TITLE
Update HEX values on Typography page

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#109]
As reported by @egunther39 

![unnamed](https://user-images.githubusercontent.com/1212885/167850836-5eedecc9-541d-4377-9278-ca2af8c1996f.png)

cc @enowak1031

**Comment by coliff** [comment]
Hi - does this look ok? If so I'll make a PR

![image](https://user-images.githubusercontent.com/1212885/167853320-0e316304-cd3a-4dc8-9c17-8b3f946e97a6.png)

**Comment by egunther39** [comment]
yep! Thanks!
