### ISSUE TITLE
Add a news article about the latest Modus bootstrap and Modus react bootstrap versions

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus.trimble.com#142]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/website-modus.trimble.com/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/website-modus.trimble.com/blob/main/.github/CONTRIBUTING.md)

### Proposal

https://modus.trimble.com/news/

**Comment by msankaran0712** [comment]
@enowak1031 Please review https://deploy-preview-158--modus-trimble.netlify.app/news/2022-06-30-modus-react-bootstrap-v110/

**Comment by enowak1031** [comment]
Looks great! Let's publish!
