### ISSUE TITLE
Fix Tooltip Background Color in Style Guide Image

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#152]
https://modus.trimble.com/components/tooltips/

It should be Gray 7 - `#585C65` but it's showing as `#595868`

**Comment by coliff** [comment]
FYI: I'll get this fixed in Modus Bootstrap v1.5.2 shipping very soon.
(but not the graphic for the style guide which this issue is for)

**Comment by enowak1031** [comment]
![Image](https://user-images.githubusercontent.com/97305117/178017120-3d595e22-cfd4-4747-8191-26953c2b9485.png)

We need to replace the image to show the correct gray color.
