### ISSUE TITLE
Spinners page 'Loading button' example should be disabled

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#156]
If the current state is loading then it suggests that the user needs to wait, therefore the button should be disabled.

What do you think @enowak1031 @egunther39 ?

Should we add disabled state to the button here:
https://modus.trimble.com/components/spinners/#specifications ?

See Bootstrap v5 docs here for explanation/example:
https://modus-bootstrap.netlify.app/docs/5.2/components/spinners/#buttons

**Comment by enowak1031** [comment]
The button should be disabled.
