### ISSUE TITLE
Create replacement images for component previews

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#160]

**Comment by enowak1031** [comment]
800x300px, both light and dark mode

**Comment by coliff** [comment]
Hi @soniakaukonen? Do you have these images ready yet? Should this be in Sprint 43?

**Comment by soniakaukonen** [comment]
I mentioned it I need both dark mode branches approved. Planned to start with 12 first components this week as branch is approved already. Best would be to implement all thumbnails at once on the style guide @coliff
