### ISSUE TITLE
Content tree font color code in dark theme is incorrect

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus.trimble.com#268]
I believe the font color code mentioned for different states in the dark theme is incorrect, @soniakaukonen @coliff Please comment. 

![image](https://user-images.githubusercontent.com/50131391/200244551-97c3b270-61c1-4d59-ae88-e787deba81a6.png)
 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

**Comment by soniakaukonen** [comment]
@msankaran0712 

Fill is correct, except: 
- selected is #019AEB 30% Trimble Dark Mode Blue with solid border #019AEB
- Disabled is Gray 10 #171C1E

Borders top bottom:
- Gray 8 #464B52

Font is #ffffff white, except:
- disabled - here I have a clash, XD is 40% white ffffff and Figma is Gray 4 solid. I assume the transparent is correct, only icons and chevrons are Gray 4 #90939F.
