### ISSUE TITLE
In-Field docs general clean up

### ISSUE THREAD

**Issue by mjohnsnz** [trimble-oss/website-modus.trimble.com#303]
- [x] Inputs style - Needs to talk about label above or side. @mjohnsnz 
- [x] Radio button Styles- Replace spec image with table @mjohnsnz
- [x] Tabs styles- update spec Table and remove current image @mjohnsnz
- [x] Update all tables to have the assets centred Horizontally and vertically (@coliff)
- [x] Segmented controls Style- State table fix both default images incorrect.  No small outline around active button @mjohnsnz
- [x]  Fix typo on this image at the top - boarder color should be border color.
https://modus.trimble.com/components/in-field/lists/styles/#specifications
need fix for light and dark mode images @mjohnsnz

**Comment by coliff** [comment]
Issues fixed:

- [x] Overview- Relink all images to have dark-mode version (@mjohnsnz)
- [x] Dropdown style- remove table image (@mjohnsnz)
- [x] Dropdown style- Change word click to tap. (@mjohnsnz)
- [x] Card style - State table has an extra column that need to be removed (@coliff)
- [x] Check box style - table spec focus image is dark theme (@mjohnsnz)
- [x] Check box style - table dark image default spec missing (@mjohnsnz)
- [x] Chips style state table chip size need to be reduced (@mjohnsnz)
- [x] Inputs style - delete active row in states table (@coliff)
- [x] Inputs style - Dark mode all images are using light mode apart from error (@coliff)
- [x] Inputs style - reduce sizes @mjohnsnz 
- [x] Message Usage- Delete extra table image, now has two tables. (@coliff)
- [x] Modals-Usage- Light mode top images showing as dark mode (@coliff)
- [x] Navbar Style- State table default pressed and disabled are missing Dark and Light @mjohnsnz 
- [x] Notification Usage-update background top image @mjohnsnz 
- [x] Prompt style- OEM branding dark mode image using light mode image (@coliff)
- [x] Segmented controls Usage- Dark mode using light mode image (@coliff)
- [x] Segmented controls Style - Dark mode OEM image is light mode
- [x] Sliders Styles - combinations - dark mode images light mode @mjohnsnz 
- [x] Sliders Styles - light mode image currently image needs fixing @mjohnsnz 
- [x] Sliders Usage - light top image does not seem update with the new image.@mjohnsnz 
- [x] Switches Usage - update top image with the updated. @mjohnsnz 
- [x] Switches Styles - Update tables and change global blue colour @mjohnsnz
