### ISSUE TITLE
Improve Dropdown Menu on Navbar

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#335]
The dropdown menu for components on our site (https://modus.trimble.com/) is quite uninspiring.

It'd be great to make it nicer with an icon and a short tagline alongside each component type (XR, Mobile, Web etc).

Storybook has a nice one for inspiration:
![image](https://user-images.githubusercontent.com/1212885/206738065-b87c047e-e67c-4546-9aa0-742e28ed9137.png)

**Comment by coliff** [comment]
I've got this so far, but think we can make it look nicer.
![image](https://user-images.githubusercontent.com/1212885/207806227-e4cd2cea-4ac1-479a-bb08-7ebca11cd562.png)

- Maybe the icons could be in color?
- @enowak1031 - would you like to provide a short tagline for the components (web and in-field for now, but we'll need XR and Mobile later)

**Comment by enowak1031** [comment]
### Web
The web library of Modus components for designing and developing web-based applications and workflows. 

### In-Field
The in-field, high-contrast library is specific to applications used outdoors on handheld or in-cab devices. 

### Mobile
UI patterns for designing Trimble experiences on Android devices.  

### XR
Building blocks for designing Trimble products for mixed reality and virtual reality. 

### Desktop 
The desktop Modus library for application that run on a computer or device locally and are built to be installed in the environment of the device’s operating system (i.e. Microsoft Windows).
