### ISSUE TITLE
Year in Review Announcement

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#359]
- We had as many as 10 Tiger Teams running at the same time with over 60 designers contributing to expand and improve the design system. Thank you for all your help and support! 
- With your help, we added 10 components and patterns to Modus. 
- We increased adoption by 100% (and that's only counting the products we are directly aware of). Most likely there are a few more product teams that have started either thinking about adoption or formerly added it to their roadmaps. 
- Dark mode is now available in Modus, both UI kits, and code components. 
- We expanded our offering of patterns to include in-field, bringing Rosetta and Modus together. Thank you, Mathew Johns, for your great work and Ken Beatson for supporting the effort. 
- We are in the process of adding mobile patterns and XR patterns into Modus. Big thanks to JuanSebastian Gomez for contributing XR patterns and to Dara Bedick and the Mobile Tiger Team for the awesome effort contributing mobile patterns. **COMING SOON!**
- We have started the effort of working on desktop patterns. Thank you, Jeremy Kerbs, and the Desktop Tiger Team for volunteering to tackle this huge project. 
- We have better organized the content on the site to accommodate the additions of in-field and other platform patterns and to make reading easier. 
- We have prepared the platform for hosting our brand new icon library. Thank you, Christian Oliff and Nick Springer for setting it up and Eric Gunther and the Icons Tiger Team for finalizing the new sets.  **COMING SOON!** 
- We started to revise our components based on Figma analytics and your feedback. Almost 10 interviewees contributed to fixes or development ideas in over 10 components in the Figma UI Kit.  Thank you so much to all who contributed!
- We have formed and formalized the new Modus Advisory Charter to help us lead the Modus effort and garner further support. Thank you, Marita Franzke and Tyler Bernard, for helping organize it and get it off the ground. 

Fill out the survey! https://forms.gle/yBFkBpugp2Yo93j89

**Comment by coliff** [comment]
looks good! A couple of suggestions/ideas:
- on the first one, should we say something like 'with over 60 designers and developers'
- Should we add a new bullet along the lines of 'We shipped many updates to the Modus Bootstrap, Modus React Bootstrap and Modus Web Components libraries with many fixes, improvements and new features'
