### ISSUE TITLE
Add hex values for colors in the Styles tab for all components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#362]
Add hex values into tables in the Styles tabs

- [x] Accordions
- [x] Alerts
- [x] Autocomplete
- [x] Badges
- [x] Breadcrumbs
- [x] Buttons
- [x] Cards
- [x] Chips
- [x] Checkboxes
- [x] Content Tree
- [x] Date & Time Picker
- [x] Dropdowns
- [ ] File Upload Dropzone
- [x] Inputs
- [x] Lists
- [x] Messages
- [x] Modals
- [x] Navbars
- [x] Pagination
- [x] Progress Bars
- [x] Radio Buttons
- [x] Side Navigation
- [x] Sliders
- [x] Spinners
- [x] Switches
- [x] Tables
- [x] Tabs
- [x] Toasts
- [x] Tooltips

**Comment by coliff** [comment]
for the dark mode bottom-border do you mean focus state? Please confirm. Right now the default bottom-border in dark mode is `#464b52` grey not blue.

**Comment by soniakaukonen** [comment]
Yes, focus state only @coliff .
