### ISSUE TITLE
Fix Disabled checkbox in Style Guide (dark)

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#410]
Disabled, unchecked should have transparent fill (being corrected in Figma, correct in XD)

**Comment by enowak1031** [comment]
@soniakaukonen Does this still need to be fixed?

**Comment by coliff** [comment]
I think this info may be out-of-date. It's not transparent in latest Figma.

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1212885/d135afa8-8d60-46c3-b6ac-3e2f1c1f1bf0)
