### ISSUE TITLE
Fix focus states and tabbing order on navbar

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#423]
- [ ] The focus needs to be white. The blue is hardly distinguishable. 
- [ ] Tabbing order skips Components menu item

![Image](https://user-images.githubusercontent.com/97305117/218146384-57ebe1b4-5182-47a3-b393-374d8eea5e1f.png)

**Comment by coliff** [comment]
This should be easy to fix tabbing order as it works correctly on Bootstrap v4.6 docs:
https://getbootstrap.com/docs/4.6/components/navbar/#supported-content
