### ISSUE TITLE
Adjust font size recommendation in the bubble for Pagination and Modals on Style Guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#439]
- [ ] Pagination large has font 20 px size - correct text in bubble (16 to 20 px)
- [ ] Modals have header 16 px size - correct text in bubble (14 to 16 px)

**Comment by coliff** [comment]
Are the correct sizes specified in the Style guide? if so:

- Pagination Large is 20px in Modus Bootstrap so need to fix it there too.
REF: https://modus-bootstrap.trimble.com/components/pagination/#large

- Modal Header is 16px in Modus Bootstrap so need to fix there too.
https://modus.trimble.com/components/web/modals/styles/

**Comment by soniakaukonen** [comment]
@coliff Specified. The sizes displayed are correct, the text in the bubble is not. It says:
font-size: 14px for the modal header (should display 16 px)
font-size: 16px for the large pagination (should display 20 px)

I can take this one for editing the style guide text.

**Comment by coliff** [comment]
Ah ok got it. I see where it needs editing for Paginations:
https://github.com/trimble-oss/website-modus.trimble.com/blob/main/content/components/web/pagination/styles.md?plain=1#L133

Not sure about Modals though, the size for that is displayed automatically by reading the styles so looks like maybe a bug.
