### ISSUE TITLE
Sentiment Scale in Style Guide

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#449]
Submission from e-Builder (contact Alex Infante)

Sentiment Scales are a quick way to collect user feedback on the experience of a tool/feature in a way that is easy to understand and promotes high response rates to increase satisfaction.

Needing to measure satisfaction with a web or mobile experience

- The format and layout of a sentiment scale are the same as a Card. 
- Titles may serve as the question and the Subtitle is neither required nor recommended. 
- Sentiment Scales should not be less than a 5-point scale. 
- Chips (Additional Tags) are optional. This should always be optional to the user and should not impact the results; this is purely supplemental.

Figma file: https://www.figma.com/file/58JEI3o2E4Kv9gvg4wDT8D/NorthStar-components-%26-patterns?node-id=2010%3A149

Documentation: https://docs.google.com/forms/d/154_JDYhxK6ydFWFhFEqIbbza1oza_tTY5OmgL8KNusA/edit#response=ACYDBNiZGLhRVPOFkkwLEhGlnQfRuZI0c6a1E4Vk4g8R2zp5Ba8Jqt4qNJtgZc2nev4X2Dc

**Comment by enowak1031** [comment]
@egunther39 We need icons for this.

**Comment by soniakaukonen** [comment]
Style guide text draft for your review @enowak1031 

https://docs.google.com/document/d/1iw7mk4EWUtnjAgGOTavBs-03FHftZE9QqIM68kG0sUw/edit# 

***

Documented also on Clickup https://app.clickup.com/t/8669zwvrk
