### ISSUE TITLE
Input and Button group in Style Guide

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#451]
Submitted by David Silcock

**Amendement**
- Having an interactive search button inside the field. It means we don't need to add an extra button outside of the field to search. It just looks a lot cleaner in my opinion.
- Just added the option to have a button on the right of the inside field
- Adding a 24px x 24px button to the write of a text input field.
- Has a hover and pressed state. When clicked it will (in my case) perform the search.

![Image](https://user-images.githubusercontent.com/97305117/221261056-c2725253-ad6a-4af7-b8ff-6b48e96250e9.png)

**Comment by msankaran0712** [comment]
@egunther39 @enowak1031 @coliff @soniakaukonen 
as discussed we need more clarity on the specs and whether we need states

**Comment by msankaran0712** [comment]
It was discussed that there is a potential usability issue with an interactive search button.

@enowak1031 @egunther39 Please correct me if am wrong.

**Comment by enowak1031** [comment]
@soniakaukonen Did we talk with David about this?

**Comment by soniakaukonen** [comment]
@enowak1031 @msankaran0712 Yes as agreed I I informed David a while ago that it has been rejected for the above mentioned reason. David referred that style guide offers the input with text button, but it is not the same as button icon within the input field. Do I need to clarify more with him?

**Comment by enowak1031** [comment]
Rejected by MoAB. Closing this issue.
