### ISSUE TITLE
Animations - Add Loading buttons to Buttons component in Styleguide

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus.trimble.com#496]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/website-modus.trimble.com/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/website-modus.trimble.com/blob/main/.github/CONTRIBUTING.md)

### Proposal

Remove the loading button from the spinners section, and add it to the buttons section

Reference: https://docs.google.com/presentation/d/11_9cEcx2itU40dzHKfvmtT360QAQUJIZYIa4Q-bxQ9k/edit#slide=id.g215cd9aef80_0_283

**Comment by soniakaukonen** [comment]
Consolidated on: https://github.com/trimble-oss/website-modus.trimble.com/issues/493
