### ISSUE TITLE
Broken icons on style guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#507]
Correct broken icons:

- [x] on Tooltips/Styles page, overlay and lack of tooltip

![Image](https://user-images.githubusercontent.com/101354258/230000845-9d42a4ea-d457-4f79-9347-cf2d4583e04e.png)

- [ ] on Navbar/usage, navbar pulls outlined icons:

![Image](https://user-images.githubusercontent.com/101354258/230001257-9b3b5c92-3105-4633-9332-fd25888fd24f.png)

- [ ] On Content tree/styles, anatomy illustration (old) has a broken kebab/vertical dots

![Image](https://user-images.githubusercontent.com/101354258/230001944-58e36498-4d07-4966-bacd-cbd2468711a3.png)

- [ ] correct dimensions for the FAB button (location TBD)

![Image](https://user-images.githubusercontent.com/101354258/230002193-244b2014-b188-4223-ac9d-65d601e1a72d.png)

**Comment by egunther39** [comment]
@soniakaukonen - Here's the link to the FAB button issue. FYI - Its not an icon issue, it's a button size issue in code

**Comment by soniakaukonen** [comment]
@egunther39 I understood it this way. Do we need to separate it from the Style Guide issues for another repo?

**Comment by egunther39** [comment]
@soniakaukonen - No I dont think so since some of the other issues are code related as well

**Comment by soniakaukonen** [comment]
FAB icon, Mobile style guide, Button section, light (and dark?) mode https://modus.trimble.com/components/mobile/buttons/ @coliff

**Comment by coliff** [comment]
> FAB icon, Mobile style guide, Button section, light (and dark?) mode [modus.trimble.com/components/mobile/buttons](https://modus.trimble.com/components/mobile/buttons/) @coliff

ok, but what needs to be changed?

**Comment by soniakaukonen** [comment]
@egunther39 said: It should be a circle 56x56. Right now its 68x60 (oval)
