### ISSUE TITLE
Read-Only Input Field (Web) - Add to Style Guide

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus.trimble.com#52]
We don't currently have specs/example of a read-only field for Inputs.
https://modus.trimble.com/components/web/inputs/

**Comment by coliff** [comment]
@egunther39 @soniakaukonen 
Do we have the specs/designs for read-only inputs?

For reference Bootstrap one is here:
https://getbootstrap.com/docs/4.6/components/forms/#readonly

> Read-only inputs appear lighter (just like disabled inputs), but retain the standard cursor.

**Comment by coliff** [comment]
Will add these on Monday! thanks.
https://docs.google.com/document/d/1FYNab5Vfo7uAHg2rFYy3uB1jrMuPSEaGTqgLuFFSfqM/edit?usp=sharing
