### ISSUE TITLE
RFC: Consider removing Status page

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#554]
Our Statius page: https://modus.trimble.com/status/ was only built for web. As we now have XR, Mobile and In-Field I think we've outgrown the need to have this page. I propose hiding it from footer/sidebar.

**Comment by msankaran0712** [comment]
This page is often forgotten to update :(

**Comment by egunther39** [comment]
I tend to agree, we should hide it

**Comment by msankaran0712** [comment]
@coliff Please proceed with this issue, we have decided to hide the page.

**Comment by msankaran0712** [comment]
@coliff Please update the sprint and story points.

**Comment by msankaran0712** [comment]
Maha to create an issue for web components to add a status page.
