### ISSUE TITLE
New variants of Tooltip to Style Guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#561]
Four new variants in Style Guide, top and bottom arrows right/left

**Comment by coliff** [comment]
This functionality is part of Modus Bootstrap so adding this to the Modus style guide should be straight forward. I suggest we use Modus Bootstrap to demo this (rather than using SVG images).

https://modus-bootstrap.trimble.com/components/tooltips/#tooltip-placement

**Comment by soniakaukonen** [comment]
@coliff sounds good!

**Comment by soniakaukonen** [comment]
@coliff added a paragraph on top and bottom left right pointer into the styles section. Can you place a bootstrap illustration accordingly within this sprint as suggested? If not, I can make svg, just let me know.
