### ISSUE TITLE
Utility Panel Guidelines - Web

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/website-modus.trimble.com#565]
As a user of the design system, I want to build a side panel that's consistent with other products at Trimble to create a consistent user experience, make sure I'm on brand, and that I'm building an accessible product.

**Comment by msankaran0712** [comment]
Wait for Figma to finish

**Comment by msankaran0712** [comment]
@enowak1031  to check with Mathew if we need it for In-field
