### ISSUE TITLE
Community page: dead links fix and submission process renewal

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#579]
Many obsolete links to board, roadmap (confluence), etc. on https://modus.trimble.com/community/

- [x] UX board
- [x] Roadmap
- [x] Backlog
- [x] Get in touch

Submission process renewal
- [ ] Discord graph
- [ ] Process change
- [ ] typo
- [ ] Display Clickup kanban board

**Comment by msankaran0712** [comment]
@soniakaukonen to Add GitHub discussions link

**Comment by soniakaukonen** [comment]
@enowak1031 still some open comments.
