### ISSUE TITLE
Modus Select (web) - Incorrect full border on focus

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus.trimble.com#597]
### Describe the issue

In the https://modus.trimble.com/components/web/inputs/styles/, the select component gets a full border on focus which is incorrect.

I believe fixing in Modus Bootstrap library should fix Styleguide and React too.

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/50131391/41a748ce-ff28-4c68-b95f-24ce8f284233)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

**Comment by coliff** [comment]
This is a Modus Bootstrap bug rather than an actual Modus styleguide problem. I've made a fix for it with Modus Bootstrap so it'll be fixed on styleguide then. In meantime I can add a temporary fix by adding the fix to the sites CSS.

```css
.custom-select:focus {
    box-shadow: none;
}
```
