### ISSUE TITLE
Identify Web Components as the recommended framework

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#611]
As an engineer using the design system, I need to know which framework is recommended to use, so that I can easily understand what to build in and prevent confusion and later rework.

**Comment by enowak1031** [comment]
As an engineer using the design system, I need to know which framework is recommended to use, so that I can easily understand what to build in and prevent confusion and later rework.

**Comment by msankaran0712** [comment]
@coliff any recommendations?

**Comment by msankaran0712** [comment]
@coliff any updates on this one? We need to add 'recommended' and 'no longer supported' tags to the cards

cc @enowak1031
