### ISSUE TITLE
Modus Styleguide - Navbar - Add Search Animation

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus.trimble.com#613]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/website-modus.trimble.com/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/website-modus.trimble.com/blob/main/.github/CONTRIBUTING.md)

### Proposal

Related to https://github.com/trimble-oss/modus-web-components/issues/1115

**Comment by msankaran0712** [comment]
Replace Navbar component examples with a live search animation

**Comment by msankaran0712** [comment]
Add it https://modus.trimble.com/components/web/navbars/

**Comment by coliff** [comment]
This will be addressed with new site template/build:
https://modus-v2.netlify.app/components/web/navbars/#overview
