### ISSUE TITLE
Critical Action Button in Style Guide

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus.trimble.com#615]

**Comment by soniakaukonen** [comment]
Source material: https://app.clickup.com/t/865c9vhgf @egunther39

**Comment by soniakaukonen** [comment]
@coliff I made the set of the new state for the table in styles (buttons). Are they correct? Only outline light and dark theme differ. In dark mode we had to change the transparency of the running progress from Gray 1 in 12% to 30%.


![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/f048c80a-0041-4b9c-b309-92c55206c5f0)
![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/6f75b251-3e3f-4e49-b36f-c93c3b3ed85b)
![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/66a99398-974c-44f0-9376-78b1c7e61845)
![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/f8dc634f-b1bd-4a78-9560-e91601721353)

**Comment by soniakaukonen** [comment]
@coliff  Another help with bootstrap I need in this table: buttons > styles. 

![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/d525b0fc-53c5-4ec6-9fc5-8e2d711b27dd)

Please replace the danger text buttons in the **icon button column** with danger state **icon button** (use trash bin icon). We added them to Figma already. Red icon buttons.

**Comment by coliff** [comment]
Is this OK? If so, I'll commit to your branch:
![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1212885/4af5ae85-043a-4940-a300-a227c4d1d94f)

**Comment by soniakaukonen** [comment]
@coliff Perfect. Then anymore the Loading state (the svgs I attached here).

**Comment by soniakaukonen** [comment]
Adding Svg for Usage > Danger and Critical Action Button table:

![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/cfa452d2-c96e-43cb-bc1e-4c95bdc583ac)
