### ISSUE TITLE
Floating Toolbar in Style Guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#623]
As a user of the design system, I want to have the option to use a toolbar with actions in my product (instead of side navigation or tree structure), so that it can meet the needs of my use case.

Floating UI Foundations article with cross references to variants on component pages
https://app.clickup.com/t/865bx62m3

**Comment by soniakaukonen** [comment]
Moved to next sprint as agreed with @enowak1031

**Comment by coliff** [comment]
FYI: The Draft is locked.
