### ISSUE TITLE
Add icon-only button variants to Style Guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#655]
https://github.com/trimble-oss/modus-web-components/issues/1539 details

**Comment by msankaran0712** [comment]
Maha to make sure the issue is added for Web components

**Comment by soniakaukonen** [comment]
Added @coliff for bootstrap button code

**Comment by soniakaukonen** [comment]
Bootstrap and markup table help needed with:

Usage:
- [ ] Danger Buttons section: Remove "Type" column and "icon-only" row
- [ ] Icon-only table: add 32px size example of secondary default for icon-only, solid, outline

Styles:
- [ ] 2nd table: add examples of each size, display padding values, in bubble: icon size and radius
- [ ] Behaviors / Danger button states: remove Icon-only from the table
- [ ] Behaviors / Icon-Only button states: 
- 1st table size 32px, all states, fill last column with dark blue background #0E416C
- 2nd table, 32px, all states, make a distinction solid vs. outline as illustrated below:

**Comment by soniakaukonen** [comment]
![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/16583b08-097e-4b17-b857-1fc7e971661d)

**Comment by soniakaukonen** [comment]
Christian working on updating Modus Bootstrap styles first - lots of problems spotted. The icon-only buttons don't have box shadow and they should when focused.

**Comment by soniakaukonen** [comment]
Christian made some changes/fixes to Modus Bootstrap button code but changes are unreleased  as of yet. 
Needed for correct states in Style Guide section.

**Comment by soniakaukonen** [comment]
@coliff thanks for changing to solids.

Few comments on icon buttons cc @egunther39 :
- [ ] Usage > Icon Buttons --> change all icons in this table to secondary gray (instead of primary blue)

![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/345b6ece-32ba-4ddd-bb66-f21594bfe0b9)


- [ ] Styles > Icon-Only Buttons states don't work properly. No difference between default, hover... and black icons on dark blue background in dark mode theme (should be identical for light and dark mode page)


![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/35d11551-c0a0-4b4b-aa6c-68fb63f49fb8)

![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/b4099e82-cdd1-4324-9134-ab345973858b)

Can be inspected on Figma:

https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/branch/if8eIDl86Om8B9eBiC73fD/Modus---Web?type=design&node-id=1346-14&mode=design&t=sgT0FrJGlwXCTERU-0 --> Buttons

![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/99821615-e142-4729-83f1-4e9984c68dd7)
