### ISSUE TITLE
Add Guidelines for Button Group

### ISSUE THREAD

**Issue by Gnirps00** [trimble-oss/website-modus.trimble.com#656]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

It would be nice if we can have some guideline for toggle buttons, just like in the original react bootstrap.
Also guideline for toggle button of icons is nice to have. Good to have some example, not just apis.

### Motivation and context

There is no guideline for toggle buttons in modus page currently. And no instruction how toggle buttons of icons should look like. 
To implement these into the products, we need some guideline.

**Comment by msankaran0712** [comment]
@Gnirps00  We will be adding the guidelines for the toggle buttons group very soon.

**Comment by Gnirps00** [comment]
Hi, thank you for updates!

**Comment by msankaran0712** [comment]
Wait for Daphnee to add it to Figma

**Comment by coliff** [comment]
We have these now:
https://modus.trimble.com/components/web/button-groups/
