### ISSUE TITLE
Correct text color for tertiary pressed button on Style Guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#670]
Tertiary pressed button (Button > Styles) has white label. Both light and dark mode.
Should be Trimble Gray `#252a2e`

Also, there is no header label for some columns

![Image](https://github.com/trimble-oss/website-modus.trimble.com/assets/101354258/f7b3ab1e-808c-440b-9f4f-4c8365433571)

**Comment by msankaran0712** [comment]
@coliff when do you want to take this issue and you can add story points.

**Comment by coliff** [comment]
This is a website bug rather than an issue with Modus Bootstrap. I'll add a CSS override to fix it on the site.
