### ISSUE TITLE
Card guidelines renewal on Style Guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#687]
Tiger Team submission:

https://www.figma.com/file/Ztqik591sfzwrJK4lJvE22/Component-Improvements-Tiger-Team?type=design&mode=design&t=JiOMmOBbRxssjBOH-0

**Comment by msankaran0712** [comment]
Moving this to the backlog as discussed in the Sprint planning

**Comment by coliff** [comment]
Changes needed:

- card title: `font-weight: 600;`
