### ISSUE TITLE
Remove 8px padding from the dropdown list

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus.trimble.com#748]
### Describe the issue

As confirmed by @egunther39, below is wrong and there is need for left/right padding
![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/50131391/5a1c51d3-a17a-4aad-a7fe-375846493b1d)

Should be fixed on Modus Styleguide and Modus Bootstrap sites
 

### What operating system(s) are you seeing the problem on?

Windows

**Comment by coliff** [comment]
I don't see any examples, screenshots or guidance that suggests using left or right padding so unsure what needs to be changed.

REF:
- https://modus.trimble.com/components/web/dropdowns/styles/
- https://modus-bootstrap.trimble.com/components/dropdowns/

**Comment by msankaran0712** [comment]
@coliff I can see it on the Navbar 
![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/50131391/4c9a897c-4af7-4122-8e5d-521b28efb1fe)

**Comment by coliff** [comment]
ah, gotcha. I can fix that then.

**Comment by coliff** [comment]
Can this be closed now?
