### ISSUE TITLE
Change 'Modus Style Guide' to 'Modus Design System' in navbar?

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#77]
Realised today that modus site says **Modus Style Guide** in the navbar but the title, description and homepage says **Modus Design System**.

Shall we change the navbar to **Modus Design System**?

**Comment by msankaran0712** [comment]
I believe the term Modus Design System includes all the frameworks, maybe change the title and description to Modus Styleguide.
