### ISSUE TITLE
Toasts: Font-weight specs error?

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#806]
### Describe the issue

Style guide states that Toasts should be semi-bold (https://modus.trimble.com/components/web/toasts/styles/#specifications), but the Figma file has Toasts as normal font-width. Should we update style guide?

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1212885/974b2d48-9216-4835-aa4a-b1d2fd756767)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

**Comment by egunther39** [comment]
Yes please

**Comment by coliff** [comment]
Fixed!
