### ISSUE TITLE
Update Toasts documentation

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus.trimble.com#876]
Toasts docs needs to be updated:
https://modus.trimble.com/components/web/toasts/

Potential issues:

- Styleguide says toasts can be any width, but Figma has width: 370px. Is there a default or minimum?
- "Toasts fade out automatically after 30 seconds." - is that still correct?

**Comment by enowak1031** [comment]
- A full width toast seems weird to me. I would say we should keep it at 370px. 
- I have no reason to believe otherwise. 

@egunther39 Eric should check it but meanwhile let's change the width to 370px and merge.

**Comment by coliff** [comment]
It's quite cramped when a button is used in addition to the close button... e.g.

![image](https://github.com/user-attachments/assets/78b9ef0a-81cc-4256-8c5b-1d2e5b08fab2)

**Comment by coliff** [comment]
@egunther39 
Modus Web Components Toasts fade out after 15 seconds (by default, but is adjustable).
The styleguide says 30 seconds... should we update one or the other?

**Comment by egunther39** [comment]
@coliff - Update styleguide for 15sec
